/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        civic: {
          blue:     '#1A3A6B',
          blueLight:'#2563EB',
          saffron:  '#FF9933',
          green:    '#138808',
          white:    '#FFFFFF',
          cream:    '#FFF9F0',
          gold:     '#F59E0B',
          slate:    '#1E293B',
          muted:    '#64748B',
        },
        background: '#f9f9ff',
        error: '#ba1a1a',
        error_container: '#ffdad6',
        inverse_on_surface: '#f0f0f7',
        inverse_primary: '#aac7ff',
        inverse_surface: '#2e3036',
        on_background: '#191c20',
        on_error: '#ffffff',
        on_error_container: '#93000a',
        on_primary: '#ffffff',
        on_primary_container: '#9bbfff',
        on_primary_fixed: '#001b3e',
        on_primary_fixed_variant: '#00468c',
        on_secondary: '#ffffff',
        on_secondary_container: '#fffbff',
        on_secondary_fixed: '#3e001d',
        on_secondary_fixed_variant: '#8e0049',
        on_surface: '#191c20',
        on_surface_variant: '#424751',
        on_tertiary: '#ffffff',
        on_tertiary_container: '#ffaa7a',
        on_tertiary_fixed: '#331200',
        on_tertiary_fixed_variant: '#763300',
        outline: '#737782',
        outline_variant: '#c2c6d3',
        primary: '#00356e',
        primary_container: '#0a4c95',
        primary_fixed: '#d6e3ff',
        primary_fixed_dim: '#aac7ff',
        secondary: '#b5005f',
        secondary_container: '#db2378',
        secondary_fixed: '#ffd9e2',
        secondary_fixed_dim: '#ffb1c7',
        surface: '#f9f9ff',
        surface_bright: '#f9f9ff',
        surface_container: '#ededf4',
        surface_container_high: '#e7e8ee',
        surface_container_highest: '#e2e2e9',
        surface_container_low: '#f3f3fa',
        surface_container_lowest: '#ffffff',
        surface_dim: '#d9d9e0',
        surface_tint: '#285ea8',
        surface_variant: '#e2e2e9',
        tertiary: '#5d2700',
        tertiary_container: '#803800',
        tertiary_fixed: '#ffdbc9',
        tertiary_fixed_dim: '#ffb68d',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['"Baloo 2"', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        'bounce-slow': 'bounce 2s infinite',
        'pulse-slow':  'pulse 3s infinite',
        'float':       'float 3s ease-in-out infinite',
        'slide-up':    'slideUp 0.4s ease-out',
        'fade-in':     'fadeIn 0.5s ease-out',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-8px)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
